# config.yaml
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1

log:
  level: "INFO"

openai:
  api_key: "${OPENAI_API_KEY}"
  base_url: ""
  models:
    - "gpt-3.5-turbo"
    - "gpt-4"

anthropic:
  api_key: "${ANTHROPIC_API_KEY}"
  models:
    - "claude-3-haiku-20240307"
    - "claude-3-sonnet-20240229"

google:
  api_key: "${GOOGLE_API_KEY}"
  models:
    - "gemini-pro"

zhipu:
  api_key: "${ZHIPU_API_KEY}"
  models:
    - "glm-4"

deepseek:
  api_key: "${DEEPSEEK_API_KEY}"
  models:
    - "deepseek-chat"

volcengine:
  access_key: "${VOLC_ACCESS_KEY}"
  secret_key: "${VOLC_SECRET_KEY}"
  models:
    - "doubao-pro-32k-240515"
