system:
  key: "854"  # 你设置的 API 访问密钥
  host: "0.0.0.0"
  port: 8000

provider:
  openai:
    base_url: "https://854.zeabur.app"  # 你的 Gemini 中转站地址
    key: "854"  # 这里填写 Gemini 的 API Key

model:
  gemini-2.5-pro:
    name: "Gemini 2.5 Pro Preview"
    provider: openai
    model: "gemini-2.5-pro-preview-06-05"
    rpm: 10
    feature:
      summary_think: true
      
  gemini-2.0-flash:
    name: "Gemini 2.0 Flash"
    provider: openai
    model: "gemini-2.0-flash"
    rpm: 30

  gemini-1.5-pro:
    name: "Gemini 1.5 Pro"
    provider: openai
    model: "gemini-1.5-pro"
    rpm: 15
